### ISSUE TITLE
QXcbConnection: Could not connect to display 10.130.8.49:0.0

### ISSUE THREAD

**Issue by wonderly321** [thunil/tempoGAN#1]
远程连接服务器：运行./manta ../scenes/simpleplume.py得到
test@vrlab:~/code/tempoGAN/build$ ./manta ../scenes/simpleplume.py
Version: mantaflow 0.12 64bit fp1 omp commit e26631d9ef6736a12b9226c928087985ee7debb5 from Aug 31 2018, 10:12:29
QXcbConnection: Could not connect to display 191.130.18.49:0.0
已放弃 (核心已转储)

**Comment by RachelCmy** [comment]
Thank you for the feedback.
It is a problem with mantaflow CMake settings.
On a remote server, GUI is not supported.
Instead of "cmake .. -DGUI=ON -DOPENMP=ON", 
please try "**cmake .. -DGUI=OFF -DOPENMP=ON -DNUMPY=ON**".
