### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[16,128,64,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

### ISSUE THREAD

**Issue by wonderly321** [thunil/tempoGAN#2]
Run example_run_training.py(batchsize  has changed to 4) with 120 frames data generated by gen_sim_3dtraining.py,It is occured that:
Resource exhausted: OOM when allocating tensor with shape[16,128,64,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

**Comment by youxie** [comment]
Hi, thanks for running our code.
yes, for 3d training, batchsize 4 might cause OOM issue. in our test, we used two GPUs(1080 Ti, 11G), and batchsize is 1(limited by memory). For more details about training parameters, you could also check them out in our paper.
Hope it would be helpful:)
Best Wishes!

**Comment by wonderly321** [comment]
Thanks very much!
But why the default batchsize is 128?And how many frames do you use to train in your test while the training time is 9 days?

**Comment by youxie** [comment]
Hi,
With data augmentation, we did not use too many frames for training(data of 96 frames for 3d training).
For more settings about parameters, you could also check them out in the appendix of our paper:)
Hope it would be helpful:)
Best Wishes!
