### ISSUE TITLE
copyGridToArrayReal not found

### ISSUE THREAD

**Issue by Schizo** [thunil/tempoGAN#3]
As someone from VFX I wanted to evaluate tempoGan but hit an issue when I was about to generate sim data using `manta ../datagen/gen_sim_data.py basePath ../2ddata_sim/ reset 1 savenpz 1`, the script errored with `NameError: name 'copyGridToArrayReal' is not defined`

Any hints?

**Comment by RachelCmy** [comment]
It could be that mantaflow is compiled without numpy support.
You can try:
`cd manta/build`
`cmake .. -DOPENMP=ON -DNUMPY=ON`
`make -j4`
if you have Qt, you can also try -DGUI=ON, but this is not necessary for tempoGAN.
